### ISSUE TITLE
bug(scope): "subdomain" in s3 bucket reported by OneForAll

### ISSUE THREAD

**Issue by psyray** [Security-Tools-Alliance/rengine-ng#175]
### Current Behavior

OneForAll's CSV has a an unfiltered header row, leading to "subdomain" being reported and used for s3 bucket's

### Expected Behavior

Not having a s3 bucket named subdomain in my interface
![image](https://github.com/user-attachments/assets/6fbb6c6a-d35f-4bd7-bcdf-34948271549a)

### Steps To Reproduce

Run this scan engine on any target
```yaml

subdomain_discovery: {
  'uses_tools': ['oneforall'],
  'enable_http_crawl': true,
  'threads': 30,
  'timeout': 5,
}
vulnerability_scan: {
  'run_nuclei': false,
  'run_dalfox': false,
  'run_crlfuzz': false,
  'run_s3scanner': true,
  'enable_http_crawl': true,
  'concurrency': 50,
  'intensity': 'normal',
  'rate_limit': 150,
  'retries': 1,
  'timeout': 5,
  'fetch_gpt_report': true,
  'nuclei': {
    'use_nuclei_config': false,
    'severities': ['unknown', 'info', 'low', 'medium', 'high', 'critical'],
  }
}
```

### Environment

```markdown
- reNgine: 2.1.0
- OS: Cebian 12
- Python: 3.10
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
