### ISSUE TITLE
feat: Distribute scan across multiple VPS

### ISSUE THREAD

**Issue by psyray** [Security-Tools-Alliance/rengine-ng#41]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

With Celery we could be able to launch multiples scan from different VPS.
It could be a kill feature.

@k11h-de already made a beat test and here's the result

I have created a test lab and ran some pretty promising tests.
I want to share my findings with you.

What I have set up:

base server (10.0.0.3): 
- installed postgres
- installed redis
- installed nfs share (exposing `/srv/shared`)

2 rengine worker nodes:
- modified `.env` database section and point to shared postgres on base server
- modified docker-compose.yml and replaced `redis://redis` with `redis://<baseserver-IP>` and `volumes` to use nfs (except for postgres_data
- modified `web/celery-entrypoint.sh` and adapted all celery commands at the bottom. e.g. `-n initiate_scan_worker` to `-n initiate_scan_worker_1`. this solved log errors like `DuplicateNodenameWarning: Received multiple replies from node names: celery@remove_duplicate_endpoints_worker`
- mounted nfs server 10.0.0.3 under `/srv/shared`

**issues**:
- not able to log in to both webUIs at the same time - even with different users. Error in log "django.security.SuspiciousSession | Session data corrupted" - but its okay to login to only one of the two worker nodes

I tested the scan engine "Full scan" and everything seems to work fine: 
- screenshots are displayed in webUI of both worker nodes 
- tasks are distributed to both nodes

appendix:

changes to `.env`

```
POSTGRES_DB=rengine
POSTGRES_USER=rengine
POSTGRES_PASSWORD=xxxxxxxxxx
POSTGRES_PORT=5432
POSTGRES_HOST=10.0.0.3
```

changes to `docker-compose.yml`
```
version: '3.8'

services:
  celery:
    environment:
      - CELERY_BROKER=redis://10.0.0.3:6379/0
      - CELERY_BACKEND=redis://10.0.0.3:6379/0

  celery-beat:
    environment:
      - CELERY_BROKER=redis://10.0.0.3:6379/0
      - CELERY_BACKEND=redis://10.0.0.3:6379/0

  web:
    environment:
      - CELERY_BROKER=redis://10.0.0.3:6379/0
      - CELERY_BACKEND=redis://10.0.0.3:6379/0

volumes:
  tool_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw
      device: ":/srv/shared/tool_config"
  postgres_data:
  gf_patterns:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw
      device: ":/srv/shared/gf_patterns"
  nuclei_templates:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw
      device: ":/srv/shared/nuclei_templates"
  github_repos:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw
      device: ":/srv/shared/github_repos"
  wordlist:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw
      device: ":/srv/shared/wordlist"
  scan_results:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw
      device: ":/srv/shared/scan_results"
  static_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.3,rw
      device: ":/srv/shared/static_volume"
```

git diff 

```
git diff web/celery-entrypoint.sh
diff --git a/web/celery-entrypoint.sh b/web/celery-entrypoint.sh
index f1d49ff1..b4f71c9e 100755
--- a/web/celery-entrypoint.sh
+++ b/web/celery-entrypoint.sh
@@ -164,24 +164,24 @@ echo 'alias httpx="/go/bin/httpx"' >> ~/.bashrc
 echo "Starting Workers..."
 echo "Starting Main Scan Worker with Concurrency: $MAX_CONCURRENCY,$MIN_CONCURRENCY"
-watchmedo auto-restart --recursive --pattern="*.py" --directory="/usr/src/app/reNgine/" -- celery -A reNgine.tasks worker --pool=gevent --concurrency=30 --loglevel=info -Q initiate_scan_queue -n initiate_scan_worker &
-watchmedo auto-restart --recursive --pattern="*.py" --directory="/usr/src/app/reNgine/" -- celery -A reNgine.tasks worker --pool=gevent --concurrency=30 --loglevel=info -Q subscan_queue -n subscan_worker &
....
+watchmedo auto-restart --recursive --pattern="*.py" --directory="/usr/src/app/reNgine/" -- celery -A reNgine.tasks worker --pool=gevent --concurrency=30 --loglevel=info -Q initiate_scan_queue -n initiate_scan_worker_1 &
+watchmedo auto-restart --recursive --pattern="*.py" --directory="/usr/src/app/reNgine/" -- celery -A reNgine.tasks worker --pool=gevent --concurrency=30 --loglevel=info -Q subscan_queue -n subscan_worker_1 &
....
``` 

### Anything else?

@ocervell what do you think about it ?
I know you already implement and test in https://github.com/freelabz/secator

Maybe couple reNgine with Secator could be a simple way to do this.
But this need a lot of tests :wink:
